import { Byte, Float, Int } from "nbt-ts";

export const Registry = {
    "minecraft:worldgen/biome": {
        "value": [
        {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(0.5),
            },
            id: new Int(0),
            name: 'minecraft:the_void',
          },
          {
            element: {
              downfall: new Float(0.4000000059604645),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7907327),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.800000011920929),
            },
            id: new Int(1),
            name: 'minecraft:plains',
          },
          {
            element: {
              downfall: new Float(0.4000000059604645),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7907327),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.800000011920929),
            },
            id: new Int(2),
            name: 'minecraft:sunflower_plains',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8364543),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(0),
            },
            id: new Int(3),
            name: 'minecraft:snowy_plains',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8364543),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(0),
            },
            id: new Int(4),
            name: 'minecraft:ice_spikes',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(5),
            name: 'minecraft:desert',
          },
          {
            element: {
              downfall: new Float(0.8999999761581421),
              effects: {
                fog_color: new Int(12638463),
                foliage_color: new Int(6975545),
                grass_color_modifier: 'swamp',
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.swamp',
                },
                sky_color: new Int(7907327),
                water_color: new Int(6388580),
                water_fog_color: new Int(2302743),
              },
              precipitation: 'rain',
              temperature: new Float(0.800000011920929),
            },
            id: new Int(6),
            name: 'minecraft:swamp',
          },
          {
            element: {
              downfall: new Float(0.8999999761581421),
              effects: {
                fog_color: new Int(12638463),
                foliage_color: new Int(9285927),
                grass_color_modifier: 'swamp',
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.swamp',
                },
                sky_color: new Int(7907327),
                water_color: new Int(3832426),
                water_fog_color: new Int(5077600),
              },
              precipitation: 'rain',
              temperature: new Float(0.800000011920929),
            },
            id: new Int(7),
            name: 'minecraft:mangrove_swamp',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jungle_and_forest',
                },
                sky_color: new Int(7972607),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.699999988079071),
            },
            id: new Int(8),
            name: 'minecraft:forest',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jungle_and_forest',
                },
                sky_color: new Int(7972607),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.699999988079071),
            },
            id: new Int(9),
            name: 'minecraft:flower_forest',
          },
          {
            element: {
              downfall: new Float(0.6000000238418579),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jungle_and_forest',
                },
                sky_color: new Int(8037887),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.6000000238418579),
            },
            id: new Int(10),
            name: 'minecraft:birch_forest',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                grass_color_modifier: 'dark_forest',
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jungle_and_forest',
                },
                sky_color: new Int(7972607),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.699999988079071),
            },
            id: new Int(11),
            name: 'minecraft:dark_forest',
          },
          {
            element: {
              downfall: new Float(0.6000000238418579),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jungle_and_forest',
                },
                sky_color: new Int(8037887),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.6000000238418579),
            },
            id: new Int(12),
            name: 'minecraft:old_growth_birch_forest',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.old_growth_taiga',
                },
                sky_color: new Int(8168447),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.30000001192092896),
            },
            id: new Int(13),
            name: 'minecraft:old_growth_pine_taiga',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.old_growth_taiga',
                },
                sky_color: new Int(8233983),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.25),
            },
            id: new Int(14),
            name: 'minecraft:old_growth_spruce_taiga',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8233983),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.25),
            },
            id: new Int(15),
            name: 'minecraft:taiga',
          },
          {
            element: {
              downfall: new Float(0.4000000059604645),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8625919),
                water_color: new Int(4020182),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(-0.5),
            },
            id: new Int(16),
            name: 'minecraft:snowy_taiga',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(17),
            name: 'minecraft:savanna',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(18),
            name: 'minecraft:savanna_plateau',
          },
          {
            element: {
              downfall: new Float(0.30000001192092896),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8233727),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.20000000298023224),
            },
            id: new Int(19),
            name: 'minecraft:windswept_hills',
          },
          {
            element: {
              downfall: new Float(0.30000001192092896),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8233727),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.20000000298023224),
            },
            id: new Int(20),
            name: 'minecraft:windswept_gravelly_hills',
          },
          {
            element: {
              downfall: new Float(0.30000001192092896),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8233727),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.20000000298023224),
            },
            id: new Int(21),
            name: 'minecraft:windswept_forest',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(22),
            name: 'minecraft:windswept_savanna',
          },
          {
            element: {
              downfall: new Float(0.8999999761581421),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jungle_and_forest',
                },
                sky_color: new Int(7842047),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.949999988079071),
            },
            id: new Int(23),
            name: 'minecraft:jungle',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jungle_and_forest',
                },
                sky_color: new Int(7842047),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.949999988079071),
            },
            id: new Int(24),
            name: 'minecraft:sparse_jungle',
          },
          {
            element: {
              downfall: new Float(0.8999999761581421),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jungle_and_forest',
                },
                sky_color: new Int(7842047),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.949999988079071),
            },
            id: new Int(25),
            name: 'minecraft:bamboo_jungle',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                fog_color: new Int(12638463),
                foliage_color: new Int(10387789),
                grass_color: new Int(9470285),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(26),
            name: 'minecraft:badlands',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                fog_color: new Int(12638463),
                foliage_color: new Int(10387789),
                grass_color: new Int(9470285),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(27),
            name: 'minecraft:eroded_badlands',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                fog_color: new Int(12638463),
                foliage_color: new Int(10387789),
                grass_color: new Int(9470285),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(28),
            name: 'minecraft:wooded_badlands',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.meadow',
                },
                sky_color: new Int(8103167),
                water_color: new Int(937679),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(29),
            name: 'minecraft:meadow',
          },
          {
            element: {
              downfall: new Float(0.800000011920929),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.grove',
                },
                sky_color: new Int(8495359),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(-0.20000000298023224),
            },
            id: new Int(30),
            name: 'minecraft:grove',
          },
          {
            element: {
              downfall: new Float(0.8999999761581421),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.snowy_slopes',
                },
                sky_color: new Int(8560639),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(-0.30000001192092896),
            },
            id: new Int(31),
            name: 'minecraft:snowy_slopes',
          },
          {
            element: {
              downfall: new Float(0.8999999761581421),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.frozen_peaks',
                },
                sky_color: new Int(8756735),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(-0.699999988079071),
            },
            id: new Int(32),
            name: 'minecraft:frozen_peaks',
          },
          {
            element: {
              downfall: new Float(0.8999999761581421),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.jagged_peaks',
                },
                sky_color: new Int(8756735),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(-0.699999988079071),
            },
            id: new Int(33),
            name: 'minecraft:jagged_peaks',
          },
          {
            element: {
              downfall: new Float(0.30000001192092896),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.stony_peaks',
                },
                sky_color: new Int(7776511),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(1),
            },
            id: new Int(34),
            name: 'minecraft:stony_peaks',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(35),
            name: 'minecraft:river',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8364543),
                water_color: new Int(3750089),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(0),
            },
            id: new Int(36),
            name: 'minecraft:frozen_river',
          },
          {
            element: {
              downfall: new Float(0.4000000059604645),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7907327),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.800000011920929),
            },
            id: new Int(37),
            name: 'minecraft:beach',
          },
          {
            element: {
              downfall: new Float(0.30000001192092896),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8364543),
                water_color: new Int(4020182),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(0.05000000074505806),
            },
            id: new Int(38),
            name: 'minecraft:snowy_beach',
          },
          {
            element: {
              downfall: new Float(0.30000001192092896),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8233727),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.20000000298023224),
            },
            id: new Int(39),
            name: 'minecraft:stony_shore',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4445678),
                water_fog_color: new Int(270131),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(40),
            name: 'minecraft:warm_ocean',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4566514),
                water_fog_color: new Int(267827),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(41),
            name: 'minecraft:lukewarm_ocean',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4566514),
                water_fog_color: new Int(267827),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(42),
            name: 'minecraft:deep_lukewarm_ocean',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(43),
            name: 'minecraft:ocean',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(44),
            name: 'minecraft:deep_ocean',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4020182),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(45),
            name: 'minecraft:cold_ocean',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(4020182),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(46),
            name: 'minecraft:deep_cold_ocean',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8364543),
                water_color: new Int(3750089),
                water_fog_color: new Int(329011),
              },
              precipitation: 'snow',
              temperature: new Float(0),
              temperature_modifier: 'frozen',
            },
            id: new Int(47),
            name: 'minecraft:frozen_ocean',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(8103167),
                water_color: new Int(3750089),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
              temperature_modifier: 'frozen',
            },
            id: new Int(48),
            name: 'minecraft:deep_frozen_ocean',
          },
          {
            element: {
              downfall: new Float(1),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(7842047),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.8999999761581421),
            },
            id: new Int(49),
            name: 'minecraft:mushroom_fields',
          },
          {
            element: {
              downfall: new Float(0.4000000059604645),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.dripstone_caves',
                },
                sky_color: new Int(7907327),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.800000011920929),
            },
            id: new Int(50),
            name: 'minecraft:dripstone_caves',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.lush_caves',
                },
                sky_color: new Int(8103167),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.5),
            },
            id: new Int(51),
            name: 'minecraft:lush_caves',
          },
          {
            element: {
              downfall: new Float(0.4000000059604645),
              effects: {
                fog_color: new Int(12638463),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.overworld.deep_dark',
                },
                sky_color: new Int(7907327),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'rain',
              temperature: new Float(0.800000011920929),
            },
            id: new Int(52),
            name: 'minecraft:deep_dark',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                additions_sound: {
                  sound: 'minecraft:ambient.nether_wastes.additions',
                  tick_chance: 0.0111,
                },
                ambient_sound: 'minecraft:ambient.nether_wastes.loop',
                fog_color: new Int(3344392),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.nether_wastes.mood',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.nether.nether_wastes',
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(53),
            name: 'minecraft:nether_wastes',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                additions_sound: {
                  sound: 'minecraft:ambient.warped_forest.additions',
                  tick_chance: 0.0111,
                },
                ambient_sound: 'minecraft:ambient.warped_forest.loop',
                fog_color: new Int(1705242),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.warped_forest.mood',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.nether.warped_forest',
                },
                particle: {
                  options: {
                    type: 'minecraft:warped_spore',
                  },
                  probability: new Float(0.014279999770224094),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(54),
            name: 'minecraft:warped_forest',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                additions_sound: {
                  sound: 'minecraft:ambient.crimson_forest.additions',
                  tick_chance: 0.0111,
                },
                ambient_sound: 'minecraft:ambient.crimson_forest.loop',
                fog_color: new Int(3343107),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.crimson_forest.mood',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.nether.crimson_forest',
                },
                particle: {
                  options: {
                    type: 'minecraft:crimson_spore',
                  },
                  probability: new Float(0.02500000037252903),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(55),
            name: 'minecraft:crimson_forest',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                additions_sound: {
                  sound: 'minecraft:ambient.soul_sand_valley.additions',
                  tick_chance: 0.0111,
                },
                ambient_sound: 'minecraft:ambient.soul_sand_valley.loop',
                fog_color: new Int(1787717),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.soul_sand_valley.mood',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.nether.soul_sand_valley',
                },
                particle: {
                  options: {
                    type: 'minecraft:ash',
                  },
                  probability: new Float(0.0062500000931322575),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(56),
            name: 'minecraft:soul_sand_valley',
          },
          {
            element: {
              downfall: new Float(0),
              effects: {
                additions_sound: {
                  sound: 'minecraft:ambient.basalt_deltas.additions',
                  tick_chance: 0.0111,
                },
                ambient_sound: 'minecraft:ambient.basalt_deltas.loop',
                fog_color: new Int(6840176),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.basalt_deltas.mood',
                  tick_delay: new Int(6000),
                },
                music: {
                  max_delay: new Int(24000),
                  min_delay: new Int(12000),
                  replace_current_music: new Byte(0),
                  sound: 'minecraft:music.nether.basalt_deltas',
                },
                particle: {
                  options: {
                    type: 'minecraft:white_ash',
                  },
                  probability: new Float(0.1180933341383934),
                },
                sky_color: new Int(7254527),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(2),
            },
            id: new Int(57),
            name: 'minecraft:basalt_deltas',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(10518688),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(0),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(0.5),
            },
            id: new Int(58),
            name: 'minecraft:the_end',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(10518688),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(0),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(0.5),
            },
            id: new Int(59),
            name: 'minecraft:end_highlands',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(10518688),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(0),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(0.5),
            },
            id: new Int(60),
            name: 'minecraft:end_midlands',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(10518688),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(0),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(0.5),
            },
            id: new Int(61),
            name: 'minecraft:small_end_islands',
          },
          {
            element: {
              downfall: new Float(0.5),
              effects: {
                fog_color: new Int(10518688),
                mood_sound: {
                  block_search_extent: new Int(8),
                  offset: 2.0,
                  sound: 'minecraft:ambient.cave',
                  tick_delay: new Int(6000),
                },
                sky_color: new Int(0),
                water_color: new Int(4159204),
                water_fog_color: new Int(329011),
              },
              precipitation: 'none',
              temperature: new Float(0.5),
            },
            id: new Int(62),
            name: 'minecraft:end_barrens',
          },],
        "type": "minecraft:worldgen/biome"
    },
    "minecraft:dimension_type": {
        "value": [
            {
                element: {
                  ambient_light: new Float(0),
                  bed_works: new Byte(1),
                  coordinate_scale: 1.0,
                  effects: 'minecraft:overworld',
                  has_ceiling: new Byte(0),
                  has_raids: new Byte(1),
                  has_skylight: new Byte(1),
                  height: new Int(384),
                  infiniburn: '#minecraft:infiniburn_overworld',
                  logical_height: new Int(384),
                  min_y: new Int(-64),
                  monster_spawn_block_light_limit: new Int(0),
                  monster_spawn_light_level: {
                    type: 'minecraft:uniform',
                    value: {
                      max_inclusive: new Int(7),
                      min_inclusive: new Int(0),
                    },
                  },
                  natural: new Byte(1),
                  piglin_safe: new Byte(0),
                  respawn_anchor_works: new Byte(0),
                  ultrawarm: new Byte(0),
                },
                id: new Int(0),
                name: 'minecraft:overworld',
              },
              {
                element: {
                  ambient_light: new Float(0.10000000149011612),
                  bed_works: new Byte(0),
                  coordinate_scale: 8.0,
                  effects: 'minecraft:the_nether',
                  fixed_time: 18000n,
                  has_ceiling: new Byte(1),
                  has_raids: new Byte(0),
                  has_skylight: new Byte(0),
                  height: new Int(256),
                  infiniburn: '#minecraft:infiniburn_nether',
                  logical_height: new Int(128),
                  min_y: new Int(0),
                  monster_spawn_block_light_limit: new Int(15),
                  monster_spawn_light_level: new Int(11),
                  natural: new Byte(0),
                  piglin_safe: new Byte(1),
                  respawn_anchor_works: new Byte(1),
                  ultrawarm: new Byte(1),
                },
                id: new Int(1),
                name: 'minecraft:the_nether',
              },
              {
                element: {
                  ambient_light: new Float(0),
                  bed_works: new Byte(0),
                  coordinate_scale: 1.0,
                  effects: 'minecraft:the_end',
                  fixed_time: 6000n,
                  has_ceiling: new Byte(0),
                  has_raids: new Byte(1),
                  has_skylight: new Byte(0),
                  height: new Int(256),
                  infiniburn: '#minecraft:infiniburn_end',
                  logical_height: new Int(256),
                  min_y: new Int(0),
                  monster_spawn_block_light_limit: new Int(0),
                  monster_spawn_light_level: {
                    type: 'minecraft:uniform',
                    value: {
                      max_inclusive: new Int(7),
                      min_inclusive: new Int(0),
                    },
                  },
                  natural: new Byte(0),
                  piglin_safe: new Byte(0),
                  respawn_anchor_works: new Byte(0),
                  ultrawarm: new Byte(0),
                },
                id: new Int(2),
                name: 'minecraft:the_end',
              },
              {
                element: {
                  ambient_light: new Float(0),
                  bed_works: new Byte(1),
                  coordinate_scale: 1.0,
                  effects: 'minecraft:overworld',
                  has_ceiling: new Byte(1),
                  has_raids: new Byte(1),
                  has_skylight: new Byte(1),
                  height: new Int(384),
                  infiniburn: '#minecraft:infiniburn_overworld',
                  logical_height: new Int(384),
                  min_y: new Int(-64),
                  monster_spawn_block_light_limit: new Int(0),
                  monster_spawn_light_level: {
                    type: 'minecraft:uniform',
                    value: {
                      max_inclusive: new Int(7),
                      min_inclusive: new Int(0),
                    },
                  },
                  natural: new Byte(1),
                  piglin_safe: new Byte(0),
                  respawn_anchor_works: new Byte(0),
                  ultrawarm: new Byte(0),
                },
                id: new Int(3),
                name: 'minecraft:overworld_caves',
              },
        ],
        "type": "minecraft:dimension_type"
    },
    "minecraft:chat_type": {
        "value": [
            {
                element: {
                  chat: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.text',
                  },
                  narration: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.text.narrate',
                  },
                },
                id: new Int(0),
                name: 'minecraft:chat',
              },
              {
                element: {
                  chat: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.announcement',
                  },
                  narration: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.text.narrate',
                  },
                },
                id: new Int(1),
                name: 'minecraft:say_command',
              },
              {
                element: {
                  chat: {
                    parameters: ['sender', 'content'],
                    style: {
                      color: 'gray',
                      italic: new Byte(1),
                    },
                    translation_key: 'commands.message.display.incoming',
                  },
                  narration: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.text.narrate',
                  },
                },
                id: new Int(2),
                name: 'minecraft:msg_command_incoming',
              },
              {
                element: {
                  chat: {
                    parameters: ['target', 'content'],
                    style: {
                      color: 'gray',
                      italic: new Byte(1),
                    },
                    translation_key: 'commands.message.display.outgoing',
                  },
                  narration: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.text.narrate',
                  },
                },
                id: new Int(3),
                name: 'minecraft:msg_command_outgoing',
              },
              {
                element: {
                  chat: {
                    parameters: ['target', 'sender', 'content'],
                    translation_key: 'chat.type.team.text',
                  },
                  narration: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.text.narrate',
                  },
                },
                id: new Int(4),
                name: 'minecraft:team_msg_command_incoming',
              },
              {
                element: {
                  chat: {
                    parameters: ['target', 'sender', 'content'],
                    translation_key: 'chat.type.team.sent',
                  },
                  narration: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.text.narrate',
                  },
                },
                id: new Int(5),
                name: 'minecraft:team_msg_command_outgoing',
              },
              {
                element: {
                  chat: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.emote',
                  },
                  narration: {
                    parameters: ['sender', 'content'],
                    translation_key: 'chat.type.emote',
                  },
                },
                id: new Int(6),
                name: 'minecraft:emote_command',
              },
        ],
        "type": "minecraft:chat_type",
    }
}